name: Automated Release
on:
  push:
    tags:
      - 'v**'
      - '!v.**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'pf2ools-${{ env.RELEASE_VERSION }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig /*.github/* CNAME'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        body: "See the [Changelogs](https://pf2etools.com/changelog.html) page."
        artifacts: "pf2ools-${{ env.RELEASE_VERSION }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}